
    create table medicines (
        min_stock integer not null,
        price numeric(12,2) not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        pharmacy_id bigint,
        description varchar(1000),
        category varchar(255) not null,
        dosage_form varchar(255),
        generic_name varchar(255),
        manufacturer varchar(255) not null,
        name varchar(255) not null,
        strength varchar(255),
        primary key (id)
    );

    create table pharmacies (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        address varchar(255),
        email varchar(255) not null unique,
        license_number varchar(255) not null unique,
        name varchar(255) not null unique,
        phone_number varchar(255),
        primary key (id)
    );

    create table prescription_items (
        line_total numeric(12,2) not null,
        quantity integer not null,
        unit_price numeric(12,2) not null,
        id bigint generated by default as identity,
        medicine_id bigint not null,
        prescription_id bigint not null,
        instructions varchar(500),
        primary key (id)
    );

    create table prescriptions (
        prescription_date date not null,
        total_amount numeric(12,2) not null,
        created_at timestamp(6) with time zone not null,
        created_by_user_id bigint not null,
        id bigint generated by default as identity,
        pharmacy_id bigint not null,
        doctor_name varchar(255) not null,
        patient_name varchar(255) not null,
        prescription_number varchar(255) not null unique,
        status varchar(255) not null check (status in ('PENDING','COMPLETED','CANCELLED')),
        primary key (id)
    );

    create table purchase_order_items (
        line_total numeric(12,2) not null,
        quantity_ordered integer not null,
        quantity_received integer not null,
        unit_cost_price numeric(12,2) not null,
        id bigint generated by default as identity,
        medicine_id bigint not null,
        purchase_order_id bigint not null,
        batch_number varchar(255),
        primary key (id)
    );

    create table purchase_orders (
        amount_paid numeric(12,2) default 0.00 not null,
        order_date date not null,
        total_amount numeric(12,2) not null,
        created_at timestamp(6) with time zone not null,
        created_by_user_id bigint not null,
        id bigint generated by default as identity,
        pharmacy_id bigint not null,
        supplier_id bigint not null,
        order_number varchar(255) not null unique,
        status varchar(255) not null check (status in ('DRAFT','ORDERED','PARTIALLY_RECEIVED','RECEIVED','CANCELLED')),
        primary key (id)
    );

    create table purchase_payments (
        amount numeric(12,2) not null,
        id bigint generated by default as identity,
        paid_at timestamp(6) with time zone not null,
        purchase_order_id bigint not null,
        reference varchar(200),
        payment_method varchar(255) not null check (payment_method in ('CASH','CREDIT_CARD','MOBILE_BANKING')),
        primary key (id)
    );

    create table purchase_return_items (
        line_total numeric(12,2) not null,
        quantity integer not null,
        unit_price numeric(12,2) not null,
        id bigint generated by default as identity,
        medicine_id bigint not null,
        purchase_return_id bigint not null,
        stock_batch_id bigint not null,
        primary key (id)
    );

    create table purchase_returns (
        return_date date not null,
        total_amount numeric(12,2) not null,
        created_at timestamp(6) with time zone not null,
        created_by_user_id bigint not null,
        id bigint generated by default as identity,
        pharmacy_id bigint not null,
        purchase_order_id bigint,
        supplier_id bigint not null,
        reason varchar(500),
        return_number varchar(255) not null unique,
        primary key (id)
    );

    create table sale_item_allocations (
        quantity integer not null,
        id bigint generated by default as identity,
        sale_item_id bigint not null,
        stock_batch_id bigint not null,
        primary key (id)
    );

    create table sale_items (
        line_total numeric(12,2) not null,
        quantity integer not null,
        unit_price numeric(12,2) not null,
        id bigint generated by default as identity,
        medicine_id bigint not null,
        sale_id bigint not null,
        primary key (id)
    );

    create table sale_payments (
        amount numeric(12,2) not null,
        id bigint generated by default as identity,
        paid_at timestamp(6) with time zone not null,
        sale_id bigint not null,
        reference varchar(200),
        payment_method varchar(255) not null check (payment_method in ('CASH','CREDIT_CARD','MOBILE_BANKING')),
        primary key (id)
    );

    create table sale_return_items (
        line_total numeric(12,2) not null,
        quantity_returned integer not null,
        unit_price numeric(12,2) not null,
        id bigint generated by default as identity,
        sale_item_id bigint not null,
        sale_return_id bigint not null,
        primary key (id)
    );

    create table sale_returns (
        return_date date not null,
        total_amount numeric(12,2) not null,
        created_at timestamp(6) with time zone not null,
        created_by_user_id bigint not null,
        id bigint generated by default as identity,
        sale_id bigint not null,
        reason varchar(500),
        items_summary varchar(255),
        return_number varchar(255) not null unique,
        primary key (id)
    );

    create table sales (
        amount_paid numeric(12,2) not null,
        discount_amount numeric(12,2) not null,
        discount_percent numeric(5,2) not null,
        due_date date,
        sale_date date not null,
        total numeric(12,2) not null,
        created_at timestamp(6) with time zone not null,
        created_by_user_id bigint not null,
        id bigint generated by default as identity,
        pharmacy_id bigint not null,
        prescription_id bigint,
        items_summary varchar(255) not null,
        payment_method varchar(255) not null check (payment_method in ('CASH','CREDIT_CARD','MOBILE_BANKING')),
        sale_number varchar(255) not null unique,
        primary key (id)
    );

    create table stock_batches (
        expiry_date date not null,
        quantity integer not null,
        unit_cost_price numeric(12,2),
        id bigint generated by default as identity,
        medicine_id bigint not null,
        received_at timestamp(6) with time zone not null,
        batch_number varchar(255) not null,
        primary key (id)
    );

    create table suppliers (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        pharmacy_id bigint not null,
        address varchar(1000),
        contact_person varchar(255),
        email varchar(255),
        name varchar(255) not null,
        phone varchar(255),
        primary key (id)
    );

    create table users (
        active boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        pharmacy_id bigint not null,
        email varchar(255) not null unique,
        full_name varchar(255) not null,
        password_hash varchar(255) not null,
        phone_number varchar(255),
        role varchar(255) not null check (role in ('ADMIN','PHARMACIST','STAFF')),
        primary key (id)
    );

    create index idx_medicine_pharmacy_id 
       on medicines (pharmacy_id);

    alter table if exists medicines 
       add constraint FKbhhcuoq8hwx6nq2afmtqbvqnt 
       foreign key (pharmacy_id) 
       references pharmacies;

    alter table if exists prescription_items 
       add constraint FKacx7kmy9ksr443xpn5dccidro 
       foreign key (medicine_id) 
       references medicines;

    alter table if exists prescription_items 
       add constraint FK6uh7tdy2lv6sx34u1365acqsf 
       foreign key (prescription_id) 
       references prescriptions;

    alter table if exists prescriptions 
       add constraint FKmgm14cxw0u8qmpdsv2c1no628 
       foreign key (created_by_user_id) 
       references users;

    alter table if exists prescriptions 
       add constraint FKqkr5kul91he73hrj51k5u9hq4 
       foreign key (pharmacy_id) 
       references pharmacies;

    alter table if exists purchase_order_items 
       add constraint FKb8eixqn0uouxtyixl57mmuq3a 
       foreign key (medicine_id) 
       references medicines;

    alter table if exists purchase_order_items 
       add constraint FKo3yj8ocbw2kav38548t22hgh8 
       foreign key (purchase_order_id) 
       references purchase_orders;

    alter table if exists purchase_orders 
       add constraint FKsnldca8ivox9hh7rk4musap97 
       foreign key (created_by_user_id) 
       references users;

    alter table if exists purchase_orders 
       add constraint FKbqyrnihrglahnu83diwfuckd4 
       foreign key (pharmacy_id) 
       references pharmacies;

    alter table if exists purchase_orders 
       add constraint FKrpdasmb8y8xs5tiy4369xpinq 
       foreign key (supplier_id) 
       references suppliers;

    alter table if exists purchase_payments 
       add constraint FKx5w6r4p8657c7vr5inf9c5g6 
       foreign key (purchase_order_id) 
       references purchase_orders;

    alter table if exists purchase_return_items 
       add constraint FKvkjwu5ln9yc76ncv1gke7pwv 
       foreign key (medicine_id) 
       references medicines;

    alter table if exists purchase_return_items 
       add constraint FK39pddnn1weajlxm2bssnpwsbh 
       foreign key (purchase_return_id) 
       references purchase_returns;

    alter table if exists purchase_return_items 
       add constraint FK534yg5kb9jyj4pve1ivw55kqb 
       foreign key (stock_batch_id) 
       references stock_batches;

    alter table if exists purchase_returns 
       add constraint FKppqf2accm543exxc7di8tp4sw 
       foreign key (created_by_user_id) 
       references users;

    alter table if exists purchase_returns 
       add constraint FKg9kkrn9xkuebo5gv1b8wnayl9 
       foreign key (pharmacy_id) 
       references pharmacies;

    alter table if exists purchase_returns 
       add constraint FKon7a5pufm9dg3hp3daw6bmkvp 
       foreign key (purchase_order_id) 
       references purchase_orders;

    alter table if exists purchase_returns 
       add constraint FK3m60bx40fnvbybfh3diblu89h 
       foreign key (supplier_id) 
       references suppliers;

    alter table if exists sale_item_allocations 
       add constraint FKcfm1e3qcj635vc6jjlgm3dk7s 
       foreign key (sale_item_id) 
       references sale_items;

    alter table if exists sale_item_allocations 
       add constraint FKtplodtm71cmjeldn3xrnu4oga 
       foreign key (stock_batch_id) 
       references stock_batches;

    alter table if exists sale_items 
       add constraint FK5n4yp9pqhplomtpumrrm8yudx 
       foreign key (medicine_id) 
       references medicines;

    alter table if exists sale_items 
       add constraint FK7tcpbc5c5mpnm8fl2phl8ep7l 
       foreign key (sale_id) 
       references sales;

    alter table if exists sale_payments 
       add constraint FKe7xb7mroghqarotk8c0rryqgm 
       foreign key (sale_id) 
       references sales;

    alter table if exists sale_return_items 
       add constraint FKm6v0nxoo8c37j3cwgya3oqxwj 
       foreign key (sale_item_id) 
       references sale_items;

    alter table if exists sale_return_items 
       add constraint FK3k56n3cibbe7p8ta1vi4qsomr 
       foreign key (sale_return_id) 
       references sale_returns;

    alter table if exists sale_returns 
       add constraint FK5ky62a423djt2ngywr3tn41d4 
       foreign key (created_by_user_id) 
       references users;

    alter table if exists sale_returns 
       add constraint FKl3sgec3y7ahl3lw37yubo5xad 
       foreign key (sale_id) 
       references sales;

    alter table if exists sales 
       add constraint FKou13r0y3kcbefjitv6viog57s 
       foreign key (created_by_user_id) 
       references users;

    alter table if exists sales 
       add constraint FKmvm05njt0kb34hnsowvps11kn 
       foreign key (pharmacy_id) 
       references pharmacies;

    alter table if exists sales 
       add constraint FKmrp778xksm1veq75o6bpqtsxl 
       foreign key (prescription_id) 
       references prescriptions;

    alter table if exists stock_batches 
       add constraint FKo79puy3pitamj8kgrua5crssp 
       foreign key (medicine_id) 
       references medicines;

    alter table if exists suppliers 
       add constraint FKh4kdiimavsq5677r68n9yjcly 
       foreign key (pharmacy_id) 
       references pharmacies;

    alter table if exists users 
       add constraint FKbgq15hbsk1ltdpiymvf3hob7l 
       foreign key (pharmacy_id) 
       references pharmacies;

